<a href="https://colab.research.google.com/github/Aishwarya-114/TNSIF--AIML/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas is powerful library for data manipulation and analysis.

In [26]:
import numpy as np
import pandas as pd

In [27]:
#create series
s = pd.Series([1,2,3,4,5,6,7])
print(s)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

Descriptive Statistics

**s.describe()**: This method gives a statistical summary of the Series, including count, mean, standard deviation, minimum, maximum, and quartile values.

In [28]:

print(s.describe())

count    7.000000
mean     4.000000
std      2.160247
min      1.000000
25%      2.500000
50%      4.000000
75%      5.500000
max      7.000000
dtype: float64

# **Data Manipulation**

**s.map(func)**: Applies a function to each element in the Series.

In [29]:
mapping = s.map(lambda x :x*2)
print(mapping)
print(s)

0     2
1     4
2     6
3     8
4    10
5    12
6    14
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

**s.apply(func)**: Similar to map, but more flexible. (Can be used Data Frames as well, where as map is only for Series)

In [30]:
applies = s.apply(lambda x : x ** 2)
print(applies)
print(s)

0     1
1     4
2     9
3    16
4    25
5    36
6    49
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

**s.sort_values()**: Sorts the Series.

In [31]:
s1 = pd.Series([4,7,54,23,92,41])
sorted = s1.sort_values()
print(sorted)

0     4
1     7
3    23
5    41
2    54
4    92
dtype: int64

**s.drop(index)**: Drops specified labels from the Series.(not deletes)

In [32]:
dropped = s.drop(1)
print(dropped)
print(s)

0    1
2    3
3    4
4    5
5    6
6    7
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

# **Handling Missing Data**

**s.isnull()**: Checks for missing values, returns a Series of booleans.

**s.notnull()**: Opposite of isnull().

**s.fillna(value)**: Fills missing values with a specified value.

**s.dropna()**: Drops all rows that contain missing values.like None

In [33]:
s2 = pd.Series([2,4,6,None,np.nan,7,0])
print(s2.isnull())

print(s2.notnull())

print(s2.fillna(0))

print(s2)
print(s2.dropna())

0    False
1    False
2    False
3     True
4     True
5    False
6    False
dtype: bool
0     True
1     True
2     True
3    False
4    False
5     True
6     True
dtype: bool
0    2.0
1    4.0
2    6.0
3    0.0
4    0.0
5    7.0
6    0.0
dtype: float64
0    2.0
1    4.0
2    6.0
3    NaN
4    NaN
5    7.0
6    0.0
dtype: float64
0    2.0
1    4.0
2    6.0
5    7.0
6    0.0
dtype: float64

# Indexing, Slicing, and Filtering

**s.iloc[ ]**: Purely integer-location based indexing. (+)-left to right,(-)-right to left

In [34]:
print(s.iloc[2])  #1,2,3,4,5,6,7
print(s.iloc[-2])

3
6

**s.loc[ ]**: Label-based indexing.(only we can give positive values not negitive)

In [35]:
print(s.loc[2])
print(s.loc[1:2])

3
1    2
2    3
dtype: int64

**s[s > n]**: Filters and returns elements greater than n.

In [36]:
greater_num = s[s<=5]
print(greater_num)

0    1
1    2
2    3
3    4
4    5
dtype: int64

# Aggregation

**s.sum():** Sums up the values

**s.cumsum()**: cumulative Sum

**s.aggregate(func):** Aggregates using one or more operations. like s.aggregate(['sum','mean','std'])

In [37]:
print(s.sum())

print(s.cumsum())

print(s.aggregate(['sum','std','mean']))

28
0     1
1     3
2     6
3    10
4    15
5    21
6    28
dtype: int64
sum     28.000000
std      2.160247
mean     4.000000
dtype: float64

# creating DataFrames

In [38]:
df=pd.DataFrame({ "name":['aishu','karthik','kavya','bobby','priya'],
      "age":[21,22,23,14,25,],
       "branch":['cse','EEE','ECE','CIVIL','DS'],
       "Address":['hyd','vijag','assam','kerala','goa']})
df

      name  age branch Address
0    aishu   21    cse     hyd
1  karthik   22    EEE   vijag
2    kavya   23    ECE   assam
3    bobby   14  CIVIL  kerala
4    priya   25     DS     goa

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   age      5 non-null      int64
 2   branch   5 non-null      object
 3   Address  5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [40]:
df.describe()

           age
count   5.0000
mean   21.0000
std     4.1833
min    14.0000
25%    21.0000
50%    22.0000
75%    23.0000
max    25.0000

In [41]:
df.isnull()

    name    age  branch  Address
0  False  False   False    False
1  False  False   False    False
2  False  False   False    False
3  False  False   False    False
4  False  False   False    False

In [42]:
df.notnull()

   name   age  branch  Address
0  True  True    True     True
1  True  True    True     True
2  True  True    True     True
3  True  True    True     True
4  True  True    True     True

In [43]:
df.fillna(0)

      name  age branch Address
0    aishu   21    cse     hyd
1  karthik   22    EEE   vijag
2    kavya   23    ECE   assam
3    bobby   14  CIVIL  kerala
4    priya   25     DS     goa

In [44]:
print(df[df['age'] > 22])

    name  age branch Address
2  kavya   23    ECE   assam
4  priya   25     DS     goa

**df.shape:** The df.shape attribute of a DataFrame returns a tuple representing the dimensionality of the DataFrame. The first element of the tuple is the number of rows, and the second is the number of columns. This is useful when you need to know how large the dataset is, such as when you are preprocessing data or ensuring that data manipulations have executed correctly.